### ISSUE TITLE
Documentation and working of project

### ISSUE THREAD

**Issue by athulsnair** [farmerkeith/Solar-charger-XL4016X2#1]
Hello,   

      This is not an issue, but I'm interested in doing this project. Where can I find necessary documentation and part list, schematics??

Thanks

**Comment by farmerkeith** [comment]
All the documentation that exists can be found under the "code" tab - schematic and some limited documentation. 
Depending on your needs, you may find the design using SZBK07 more valuable. 
Please also see my Instructable on Controlling DC converter modules for more in-depth information. 
https://www.instructables.com/id/Controlling-DC-Converter-Modules/
Keith
